# Generated by Django 3.1.5 on 2021-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='covid',
            field=models.BooleanField(default=False),
        ),
    ]
