# Generated by Django 3.1.5 on 2021-02-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('tracking_id', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
                ('appointment', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(choices=[(1, 'recieved'), (2, 'confirmed'), (3, 'shipped'), (4, 'delivered')], default=1, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.customer')),
            ],
        ),
    ]
