# Generated by Django 3.1.5 on 2021-02-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
